import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideNav from "@/components/layout/SideNav";
import { ShapeProvider } from "@/lib/context/ShapeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ShapeProvider>
          <div className="flex min-h-screen relative">
            <div className="self-center mx-5  absolute">
              <SideNav />
            </div>
            {children}

          </div>
        </ShapeProvider>


      </body>
    </html>
  );
}
